# Generated by Django 5.0.3 on 2024-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='removebg',
            field=models.BooleanField(default=False),
        ),
    ]
