# Generated by Django 5.0.3 on 2024-05-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_removebg'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='goods.categories'),
        ),
    ]
